#!/usr/bin/env python3
"""Converts a fixed-cell BDF font (width <= 8) into a C++ include with Latin-1 glyphs.

Usage: tools/bdf2inc.py third_party/spleen/spleen-6x12.bdf kSpleen6x12 > arm9/source/gfx/fonts/spleen_6x12.inc

Each glyph is `height` bytes, one per row, bit 7 = leftmost pixel. Codepoints 32..255 are emitted;
missing ones copy '?'.
"""
import sys

FIRST, LAST = 32, 255


def parse(path):
    glyphs = {}
    cell = None
    with open(path, encoding="latin-1") as f:
        lines = iter(f.read().splitlines())
    for line in lines:
        if line.startswith("FONTBOUNDINGBOX"):
            w, h, xoff, yoff = map(int, line.split()[1:])
            cell = (w, h, xoff, yoff)
        elif line.startswith("STARTCHAR"):
            encoding, bbx, rows = None, None, []
            for line in lines:
                if line.startswith("ENCODING"):
                    encoding = int(line.split()[1])
                elif line.startswith("BBX"):
                    bbx = tuple(map(int, line.split()[1:]))
                elif line == "BITMAP":
                    for line in lines:
                        if line == "ENDCHAR":
                            break
                        rows.append(int(line[:2], 16))  # width <= 8: one byte per row
                    break
            glyphs[encoding] = (bbx, rows)
    return cell, glyphs


def render(cell, bbx, rows):
    cw, ch, cxoff, cyoff = cell
    gw, gh, gx, gy = bbx
    out = [0] * ch
    baseline = ch + cyoff  # rows above the baseline
    top = baseline - (gy + gh)
    shift = gx - cxoff
    for i, bits in enumerate(rows[:gh]):
        row = top + i
        if 0 <= row < ch:
            out[row] = (bits >> shift) & 0xFF if shift >= 0 else (bits << -shift) & 0xFF
    return out


def main():
    path, name = sys.argv[1], sys.argv[2]
    cell, glyphs = parse(path)
    width, height = cell[0], cell[1]
    if width > 8:
        sys.exit("fonts wider than 8 pixels are not supported")
    fallback = render(cell, *glyphs[ord("?")])
    print(f"// Generated by tools/bdf2inc.py from {path.replace(chr(92), '/')}. Do not edit.")
    print(f"constexpr int {name}Width = {width};")
    print(f"constexpr int {name}Height = {height};")
    print(f"constexpr uint8_t {name}Glyphs[{LAST - FIRST + 1}][{height}] = {{")
    for code in range(FIRST, LAST + 1):
        rows = render(cell, *glyphs[code]) if code in glyphs else fallback
        print("\t{" + ", ".join(f"0x{r:02X}" for r in rows) + f"}}, // U+{code:04X}")
    print("};")


if __name__ == "__main__":
    main()
